// Bundle the Heritage typefaces for offline rendering.
//
//   node fetch-fonts.mjs
//
// Writes public/fonts/*.woff2 and src/fontFaces.ts from one fetch, so the
// stylesheet and the files it points at can never drift apart.
//
// They did drift once. The fonts were bundled by hand, then fontFaces.ts was
// regenerated later; Google had rotated its URLs, so every @font-face pointed
// at a file that no longer existed. Nothing failed — Chrome fell back to a
// default serif and the whole film rendered in the wrong voice. The only
// symptom was a 404 line buried in the render log.
//
// Two reasons the fonts are local at all: Remotion renders across many
// parallel workers, and Google rate-limits that (it surfaces as a delayRender
// timeout, not a network error); and a render should not need the network.

import { mkdir, rm, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import path from 'node:path';

const CSS_URL =
  'https://fonts.googleapis.com/css2' +
  '?family=EB+Garamond:ital,wght@0,400;0,500;1,400' +
  '&family=IM+Fell+English:ital@0;1' +
  '&family=IM+Fell+English+SC' +
  '&display=swap';

// Google serves woff2 only to browsers it recognises; a bare fetch gets ttf.
const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 ' +
  '(KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36';

const run = async () => {
  const css = await (await fetch(CSS_URL, { headers: { 'User-Agent': UA } })).text();

  const urls = [...new Set(css.match(/https:\/\/[^)]+\.woff2/g) ?? [])];
  if (!urls.length) throw new Error('no woff2 URLs in the Google stylesheet');

  const outDir = path.join('public', 'fonts');
  await rm(outDir, { recursive: true, force: true });
  await mkdir(outDir, { recursive: true });

  let rewritten = css;
  for (const url of urls) {
    const name = `${createHash('md5').update(url).digest('hex').slice(0, 8)}.woff2`;
    const buf = Buffer.from(await (await fetch(url)).arrayBuffer());
    await writeFile(path.join(outDir, name), buf);
    rewritten = rewritten.split(url).join(`FONTBASE/${name}`);
  }

  await writeFile(
    path.join('src', 'fontFaces.ts'),
    '// Generated by fetch-fonts.mjs — do not edit. Run that script instead, so\n' +
      '// the @font-face rules and public/fonts stay in step.\n' +
      `export const FONT_FACES = ${JSON.stringify(rewritten)};\n`,
  );

  const families = [...new Set(css.match(/font-family: '([^']+)'/g) ?? [])];
  console.log(`  ${urls.length} files → ${outDir}`);
  families.forEach((f) => console.log(`    ${f.replace("font-family: ", '')}`));
};

run();
